### ISSUE TITLE
Code4Projects 0.0.1 website launch

### ISSUE THREAD

**Issue by sasadangelo** [sasadangelo/code4projects#10]
These are the required steps to execute to launch the new Code4Projects website:

**Tasks for the 0.0.1 release**

- [x] Import AWS articles
- [x] Import IBM Cloud articles
- [x] Import Bosh articles
- [x] Fix [Images cut off on mobile device](https://github.com/sasadangelo/code4projects/issues/4)
- [x] Pro and Cons table
- [x] Thank you page
- [x] Newsletter
- [x] Privacy Policy
- [x] Robots.txt file
- [x] Sitemap
- [x] Robots tags in HTML pages
- [x] Google Analytics in production code
- [x] Google Site verification in production code
- [x] 404 Page
- [x] Favicon
- [x] Draft posts
- [x] Use redirect 301 to resolve URL mismatch between old and new website
- [x] Migrate code4projects.net domain to GitHub pages
