### ISSUE TITLE
Code4Projects next releases product backlogs

### ISSUE THREAD

**Issue by sasadangelo** [sasadangelo/code4projects#18]
This is the product backlog for the next releases

## Tasks for the 0.0.4 release

- [ ] Loading lazy for images
- [ ] Number of posts in a Category
- [ ] Improve Blog and Categories pagination
- [ ] Improve images format and optimize sizes (use Google PageSpeed for help)
- [ ] Robots file
- [ ] Images in sitemap

## Tasks for the 1.0.0 release

- [ ] Tags management
- [ ] Multi authors
- [ ] Improve sitemap_index.xml loop through sitemaps and using the last modified field from the sitemap itself.
- [ ] Archives (by Time)
- [ ] Prev/Nex link in each post at the bottom of the page
- [ ] Multi language support
- [ ] Separate theme and blog
- [ ] Verify if it is possible move all images under assets/img with URL redirect
- [ ] Adsense
- [ ] Amazon Affiliates
- [ ] Powered by Jeckyll
- [ ] Figure numbers, borders, captions, copyright info
- [ ] Breadcrumbs
